### ISSUE TITLE
Suggestion: Flat Real Mode

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [ZeroKelvinKeyboard/TachyonOS#3]
Hi! I come with proposition of making TachyonOS run in unreal (flat real mode). This means, that we would have access to 4GB of memory, while having chance to use BIOS. It's really nice idea, you guys should take it into consideration

**Comment by ZeroKelvinKeyboard** [comment]
It's a nice idea, but it would be tricky to implement which the API, because a lot of it is base around BIOS calls and these don't always work with memory outside of what's accessible in real mode (the first 1 MiB).
I'll consider it.

**Comment by KrzysztofSzewczyk** [comment]
Wow, nice.
I wasn't expecting any answer anyways xD
I guess I've evolved in osdev so far that I'll be able to help in it.
You can check out my assembly unreal mode os attempt, although it doesn't work and I don't have time to debug it.

**Comment by ZeroKelvinKeyboard** [comment]
There's still a lot of bugs to fix in the previously abandoned TachyonOS, so I'll be working on that before considering any new features. 

There is a 32-bit branch of the C library for MikeOS/TachyonOS that enables huge unreal mode for user programs. Still incomplete last I left it, but if you're interesting in writing unreal mode programs for MikeOS it might help.

https://github.com/ZeroKelvinKeyboard/MikeOS-CLib/tree/32-bit

**Comment by KrzysztofSzewczyk** [comment]
Really nice!
What I'd like to see in your project is working fgetc() or fread() routine so we don't need to load whole file at once.

**Comment by ZeroKelvinKeyboard** [comment]
That's not really feasible at the moment, since the C library builds on the MikeOS API. 

libc
   |
libmikeos
  |
MikeOS API

So the C library can't do anything the MikeOS API can't do, such as loading part of a file. 

It's not possible to implemement something like fgets() because `os_load_file` API call can only load whole files.

The only way around this would be to either have a seperate disk driver or update the OS.

The former would take a lot of work and make outputted programs very large, as the driver would need to be built into program.

The latter is still a lot of work updating the OS and libraries but probably do able. It shouldn't be too difficult to implement in TachyonOS. As for MikeOS; the disk API isn't great to extend, but I have some unfinished code to eventually replace the disk parts.

So it may come eventually but not until OS support for partial loading exists. 

I'll be working on that after finishing the new BASIC interpeter.

**Comment by KrzysztofSzewczyk** [comment]
Actually, it can't be such complex - if (i hope) MikeOS supplies sector reading, it would be pretty easy to implement. Size would increase by max 5KB if driver was written correctly, that's not very much when unreal mode will be done.
