### ISSUE TITLE
Update to use MikeOS v4.6b2 (as the base)

### ISSUE THREAD

**Issue by MrDiamond123** [ZeroKelvinKeyboard/TachyonOS#6]
TachyonOS is a great improvement over MikeOS in terms of ease of use but is a little outdated in terms of libraries. 

Would you please update it to v4.6b2?

@ZeroKelvinKeyboard

**Comment by ZeroKelvinKeyboard** [comment]
I'm not updating until I see a the full 4.6 release of MikeOS (if it ever comes). It doesn't matter much anyway, as TachyonOS already has a most of the new features coming to MikeOS. Is there anything it's missing?

**Comment by thefirefox12537** [comment]
I will wait a new release of TachyonOS version. If you see the 4.6 MikeOS

**Comment by informer2016** [comment]
@ZeroKelvinKeyboard @thefirefox12537 @MrDiamond123 I also think it is a good idea to borrow the improvements from 4.6b2 - especially since it seems you did these improvements - https://groups.google.com/forum/#!topic/mikeos/6TIfE19eDi0 - and Michael Saunders was going to release your 4.6b2 as 4.6 but then forgot, I guess . Or these improvements are not compatible with TachyonOS ? Also, what about these suggestions by Nikto and Danbarry? _(at the end of Google Groups thread)_
