### ISSUE TITLE
[VirtualBox] Boot process halted with error: Error loading file (booting is not successful)

### ISSUE THREAD

**Issue by informer2016** [ZeroKelvinKeyboard/TachyonOS#9]
Compared to https://github.com/ZeroKelvinKeyboard/TachyonOS/issues/8 there are 3x FAILED now 
```
Checking for autorun binary...... FAILED
Checking for autorun BASIC program...... FAILED
and
Loading menu data file...... FAILED
```
Booting is not successful in this case and there's a message:
`Boot process halted with error: Error loading file`

**Comment by ZeroKelvinKeyboard** [comment]
The message you quoted is a boot error that occurs is the file 'MENU.TXT' does not exist in the root directory or could not be loaded. This is a fatal error, as the file contains the menu structure for the user interface and the UI can not be started without it.

**Comment by gabrielsantos20** [comment]
In the virtualbox you should start as if it were a floppy in the case of TachyonOS the floppy disks are in .ima or .flp format, but do not worry the virtualbox will read normally for me at least it worked and started without errors, it reminds a lot of systems of time since we start by diskette like for example System 7 of apple follows in annex
![VirtualBox_techyonOS_15_06_2019_14_07_52](https://user-images.githubusercontent.com/51860770/59554272-076d6200-8f77-11e9-81ec-63ee15b327aa.png)
![Captura de Tela (19)](https://user-images.githubusercontent.com/51860770/59554276-10f6ca00-8f77-11e9-8d8a-9ac842177a5c.png)
